steps:
  # Step 1: Fetch the service account key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          echo "Fetching service account key from Secret Manager"
          gcloud secrets versions access latest --secret="terraform-service-account-key" > /workspace/terraform-service-account.json

  # Step 2: Initialize Terraform
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform init

  # Step 3: Validate Terraform Configuration
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform validate

  # Step 4: Run Terraform Plan
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform plan -out=tfplan

  # Step 5: Apply the Terraform Plan
  - name: 'hashicorp/terraform:light'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform apply -auto-approve tfplan

timeout: "1200s"  # Optional: increase the timeout (default is 10 minutes)

# Optional: Add email notifications for build status
# notifications:
#   email:
#     - 'youremail@example.com'
